### ISSUE TITLE
need to sudo matrix first run after global install

### ISSUE THREAD

**Issue by eighteyes** [matrix-io/matrix-cli#4]
Maybe write the store without the folder. 
```
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/matrix-cli/lib/../tmp'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:916:18)
    at Object.getConfig (/usr/local/lib/node_modules/matrix-cli/lib/helpers.js:46:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/matrix-cli/bin/matrix-init.js:17:32)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
```

**Comment by eighteyes** [comment]
Resolved :) d686f29 ty @di3goleite
