### ISSUE TITLE
Unable to register device

### ISSUE THREAD

**Issue by ScottChapman** [matrix-io/matrix-cli#54]
```
$ matrix register device
/usr/lib/node_modules/matrix-cli/bin/matrix-validate.js:23
  var token = Matrix.config.user.token;
                                ^

TypeError: Cannot read property 'token' of undefined
    at token (/usr/lib/node_modules/matrix-cli/bin/matrix-validate.js:23:33)
    at Object.user (/usr/lib/node_modules/matrix-cli/bin/matrix-validate.js:3:3)
    at /usr/lib/node_modules/matrix-cli/bin/matrix-register.js:14:23
    at /usr/lib/node_modules/matrix-cli/node_modules/node-yaml-localize/lib/node-yaml-localize/translator.js:175:24
    at next (/usr/lib/node_modules/matrix-cli/node_modules/node-yaml-localize/lib/node-yaml-localize/translator.js:228:35)
    at /usr/lib/node_modules/matrix-cli/node_modules/node-yaml-localize/lib/node-yaml-localize/translator.js:240:25
    at FSReqWrap.oncomplete (fs.js:123:15)
```

This appears same as https://github.com/matrix-io/matrix-cli/issues/52 but solution there did not work for me. I am on current node, and current matrix-cli running on mac osx

**Comment by eighteyes** [comment]
@ScottChapman did you `matrix login`? after registering?

**Comment by ScottChapman** [comment]
Missed that step. Not in the documentation.

All set! thanks!

**Comment by eighteyes** [comment]
You are completely correct. :) Changing the docs.
