### ISSUE TITLE
Sensor Install is not working now.

### ISSUE THREAD

**Issue by adrian2lee** [matrix-io/matrix-cli#61]
While trying to install sensorTest
```
matrix install sensorTest
⡿ C:\Users\userx\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\matrix-node-sdk\adsdk.js:369
    cb(null,resp);
    ^

TypeError: cb is not a function
    at C:\Users\userx\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\matrix-node-sdk\adsdk.js:369:5
    at Socket.<anonymous> (C:\Users\userx\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\matrix-node-sdk\utils\Socket.js:28:13)
    at Socket.Emitter.emit (C:\Users\userx\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\component-emitter\index.js:133:20)
    at Socket.onClose (C:\Users\userx\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\engine.io-client\lib\socket.js:715:10)
    at close (C:\Users\userx\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\engine.io-client\lib\socket.js:651:10)
    at Socket.<anonymous> (C:\Users\userx\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\engine.io-client\lib\socket.js:640:11)
    at Socket.on (C:\Users\userx\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\component-emitter\index.js:65:8)
    at Socket.Emitter.emit (C:\Users\userx\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\component-emitter\index.js:133:20)
    at Socket.onDrain (C:\Users\userx\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\engine.io-client\lib\socket.js:544:10)
    at WS.<anonymous> (C:\Users\userx\AppData\Roaming\npm\node_modules\matrix-cli\node_modules\engine.io-client\lib\socket.js:265:10)
```

**Comment by brianofrokk3r** [comment]
Will confirm in a couple of minutes @adrian2lee

**Comment by brianofrokk3r** [comment]
@adrian2lee valid issue, will get it fixed shortly.

**Comment by brianofrokk3r** [comment]
Fixing...

**Comment by eighteyes** [comment]
@adrian2lee thanks for the heads up. this has been fixed in our latest release. `npm upgrade -g matrix-cli` `1.2.7` is what you're looking for

**Comment by adrian2lee** [comment]
Thank you, fast work guys
