### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by anthonyray** [matrix-io/matrix-cli#80]
Hi there ! 

While trying to search for apps from the matrix-cli, here is the stacktrace I get : 

```
/usr/local/lib/node_modules/matrix-cli/bin/matrix-search.js:27
<<<<<<< HEAD
^^
SyntaxError: Unexpected token <<
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

It must be an old merge conflict 😄 !
I think that as soon as tests will be passing, you will push fixes to npm ! 

Cheers!

**Comment by eighteyes** [comment]
@anthonyray thank you! it was indeed a conflict which slipped in there. i've pushed `1.3.4` to npm, which should work better.
